name: posse_gallery
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ic_flutter_logo.png
    - assets/icons/ic_search.png